services:
  data-generator:
    image: 'data-generator-test'
    build: .
    container_name: data-generator
    environment:
      DEVICE_COUNT: 300
      TAG_COUNT: 50
      HISTORY_YEARS: 3
      CONN_STRING: "postgresql://postgres:5432/TEST?user=postgres&password=TEST!timescale"
    volumes:
      - .:/app
    command: ["/bin/sh", "-c", "python /app/script.py"]
    depends_on:
      postgres:
        condition: service_healthy
    
  postgres:
    shm_size: '3gb'
    image: timescale/timescaledb-ha:pg16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TEST!timescale
      POSTGRES_DB: TEST
      # Performance tuning parameters
      max_wal_size: 8GB                     # Increased from 4GB to reduce checkpoint frequency
      min_wal_size: 2GB                     # Increased from 1GB
      shared_buffers: 1GB
      effective_cache_size: 3GB
      maintenance_work_mem: 256MB
      checkpoint_completion_target: 0.9
      checkpoint_timeout: '30min'           # Added to control checkpoint frequency
      wal_buffers: '16MB'                  # Added for better WAL performance
      random_page_cost: 1.1                # Added for better query planning
      work_mem: '64MB'                     # Added for better query performance
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data   # Changed path to standard PostgreSQL data directory

volumes:
  postgres_data:
    name: postgres_data
    # Add this driver option to always start fresh
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  default:
    name: test-network
